### ISSUE TITLE
filter is not funvction

### ISSUE THREAD

**Issue by desaipiyush68** [jonschlinkert/filter-object#3]
TypeError: filter is not a function

**Comment by doowb** [comment]
@desaipiyush68 please show the code that is causing the error.

**Comment by desaipiyush68** [comment]
var filter = require('filter-objects');
var Array =[{user:1,device:1},{user:2,device:2},{user:1,device:2}];
var filter_device ={user:1};
var data = filter(Array,filter_device);

**Comment by jonschlinkert** [comment]
please wrap code in triple backticks, it's unreadable. Also `Array` is a native class in javascript.

**Comment by desaipiyush68** [comment]
![image](https://cloud.githubusercontent.com/assets/17989170/20139588/d65e0a5e-a67e-11e6-9fdb-f40ab2f61581.png)

**Comment by desaipiyush68** [comment]
![image](https://cloud.githubusercontent.com/assets/17989170/20139720/61a4659a-a67f-11e6-9284-3f55cb9b1ea1.png)

**Comment by desaipiyush68** [comment]
```
var Ddata =[{user:1,device:1},{user:2,device:2},{user:1,device:2}];
var filter_device ={user:1};
var data = filter(Ddata,filter_device);
```

**Comment by doowb** [comment]
> `var filter = require('filter-objects');`

This library is `filter-object` not `filter-objects`

**Comment by jonschlinkert** [comment]
closing since it looks like this is the wrong library
